### ISSUE TITLE
LookUp method in class

### ISSUE THREAD

**Issue by hooramin** [KaveNegar/kavenegar-php#3]
salam
Ta oonjayi ke mostanadat ro khoondam tooye php wrapper chizi baraye look up ya hamoon system etebar sanjitoon nadidam.

agar dar php wrapper api kavenegar classi baraye in kar hast mamnoon misham rahnamyi konid.

**Comment by bgsrb** [comment]
ba salam
bale ba method VerifyLookup.
baraye nemoone :
https://github.com/KaveNegar/kavenegar-examples-php/blob/master/src/VerifyLookup.php

**Comment by hooramin** [comment]
Mamnoonam , search nakarde boodam.
